server:
  port: 8080

spring:
  application:
    name: gateway-service

  config:
    import: optional:nacos:gateway-service.yml

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.129:8848
      config:
        server-addr: 192.168.200.129:8848
        file-extension: yml

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      # 全局超时配置
      httpclient:
        connect-timeout: 10000
        response-timeout: 30s
      # 路由配置
      routes:
        # 用户服务路由
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=0
        # 认证服务路由
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        # 动态服务路由
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/post/**
        # 活动服务路由
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/event/**
        # 聊天服务路由
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/chat/**
        # AI审核服务路由
        - id: ai-audit-service
          uri: lb://ai-audit-service
          predicates:
            - Path=/api/audit/**
        # 消息服务路由
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/message/**
        # 推荐服务路由
        - id: recommend-service
          uri: lb://recommend-service
          predicates:
            - Path=/api/recommend/**


# Redis 配置
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 5000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

# JWT 配置
jwt:
  secret: youthconnect-secret-key-2024
  expiration: 86400000 # 24小时

# 日志配置
logging:
  level:
    com.youthconnect: debug
    org.springframework.cloud.gateway: debug
